#' plot thermal habitat anomaly (spaghetti)
#'
#' Plots the Fall thermal habitat anomaly data set as a line plot for the State of the Ecosystem report.
#' Individual species are shown as faint background lines, with the aggregate average shown as a thick solid line.
#'
#' @param shadedRegion Numeric vector. Years denoting the shaded region of the plot (most recent 10)
#' @param report Character string. Which SOE report ("MidAtlantic", "NewEngland")
#'
#' @return ggplot object
#'
#' @export
#'

plot_thermal_habitat_anomaly_spaghetti <- function(
    shadedRegion = NULL,
    report = "MidAtlantic"
) {
  # generate plot setup list (same for all plot functions)
  setup <- ecodata::plot_setup(shadedRegion = shadedRegion, report = report)
  
  # which report? Route to the appropriate EPU flag generated by create_thermal_habitat_anomaly
  if (report == "MidAtlantic") {
    filterEPU <- "MA"
  } else if (report == "NewEngland") {
    filterEPU <- "NE"
  } else {
    stop("For this indicator, the report must be either 'MidAtlantic' or 'NewEngland'")
  }
  
  # Filter the data object to the appropriate region
  dat <- ecodata::thermal_habitat_anomaly |>
    dplyr::filter(EPU == filterEPU)
  
  # Calculate the annual average anomaly across all species for the thick trend line
  dat_mean <- dat |>
    dplyr::group_by(Time) |>
    dplyr::summarize(Mean_Value = mean(Value, na.rm = TRUE), .groups = "drop")
  
  # Code for generating plot object p
  # ensure that setup list objects are called as setup$...
  
  p <- ggplot2::ggplot() +
    
    # Highlight last ten years in the background
    ggplot2::annotate(
      "rect",
      fill = setup$shade.fill,
      alpha = setup$shade.alpha,
      xmin = setup$x.shade.min,
      xmax = setup$x.shade.max,
      ymin = -Inf,
      ymax = Inf
    ) +
    
    # Add a horizontal dashed line at 0 (the baseline)
    ggplot2::geom_hline(
      yintercept = 0, 
      linetype = "dashed", 
      color = "black", 
      linewidth = 0.5
    ) +
    
    # Faint individual species lines ("spaghetti")
    ggplot2::geom_line(
      data = dat,
      ggplot2::aes(x = Time, y = Value, group = Var),
      color = "grey50", 
      alpha = 0.4, 
      linewidth = 0.5
    ) +
    
    # Thick aggregate mean line
    ggplot2::geom_line(
      data = dat_mean,
      ggplot2::aes(x = Time, y = Mean_Value),
      color = "black", 
      linewidth = 1.2
    ) +
    
    ggplot2::scale_x_continuous(
      breaks = round(seq(min(dat$Time, na.rm = TRUE), max(dat$Time, na.rm = TRUE), by = 5)),
      expand = c(0.01, 0.01)
    ) +
    
    ggplot2::labs(
      y = "Fall Habitat Anomaly (%)",
      x = ggplot2::element_blank()
    ) +
    
    # Apply standard ecodata themes and titles
    ggplot2::ggtitle(paste0("Fall Thermal Habitat Anomaly \u2014 ", report, " Managed Species")) +
    ecodata::theme_ts() +
    ecodata::theme_title()
  
  return(p)
}

# Assign required ecodata attributes
attr(plot_thermal_habitat_anomaly_spaghetti, "report") <- c("MidAtlantic", "NewEngland")