#' plot thermal habitat anomaly (spaghetti)
#'
#' Plots the Fall thermal habitat anomaly data set as a line plot for the State of the Ecosystem report.
#' Individual species are shown as faint background lines, with the aggregate average shown as a thick solid line.
#' The species whose trends deviate the most from the average are highlighted in color.
#'
#' @param shadedRegion Numeric vector. Years denoting the shaded region of the plot (most recent 10)
#' @param report Character string. Which SOE report ("MidAtlantic", "NewEngland")
#' @param n_outliers Numeric. The number of outlier species to highlight in color (default is 4).
#'
#' @return ggplot object
#'
#' @export
#'

plot_thermal_habitat_anomaly_spaghetti <- function(
    shadedRegion = NULL,
    report = "MidAtlantic",
    n_outliers = 4
) {
  # generate plot setup list (same for all plot functions)
  setup <- ecodata::plot_setup(shadedRegion = shadedRegion, report = report)
  
  # which report? Route to the appropriate EPU flag generated by create_thermal_habitat_anomaly
  if (report == "MidAtlantic") {
    filterEPU <- "MA"
  } else if (report == "NewEngland") {
    filterEPU <- "NE"
  } else {
    stop("For this indicator, the report must be either 'MidAtlantic' or 'NewEngland'")
  }
  
  # Filter the data object to the appropriate region
  dat <- ecodata::thermal_habitat_anomaly |>
    dplyr::filter(EPU == filterEPU)
  
  # Calculate the annual average anomaly across all species for the thick trend line
  dat_mean <- dat |>
    dplyr::group_by(Time) |>
    dplyr::summarize(Mean_Value = mean(Value, na.rm = TRUE), .groups = "drop")
  
  # Identify the species that deviate the most from the average trend.
  # We do this by measuring the mean absolute difference between the species 
  # anomaly and the regional average anomaly across the time series.
  dat_diff <- dat |>
    dplyr::left_join(dat_mean, by = "Time") |>
    dplyr::group_by(Var) |>
    dplyr::summarize(
      mean_abs_diff = mean(abs(Value - Mean_Value), na.rm = TRUE), 
      .groups = "drop"
    ) |>
    dplyr::arrange(dplyr::desc(mean_abs_diff))
  
  top_outliers <- head(dat_diff$Var, n_outliers)
  
  # Split the data into background lines (grey) and outlier lines (colored)
  dat_bg <- dat |> dplyr::filter(!Var %in% top_outliers)
  dat_outliers <- dat |> dplyr::filter(Var %in% top_outliers)
  
  # Code for generating plot object p
  # ensure that setup list objects are called as setup$...
  
  p <- ggplot2::ggplot() +
    
    # Highlight last ten years in the background
    ggplot2::annotate(
      "rect",
      fill = setup$shade.fill,
      alpha = setup$shade.alpha,
      xmin = setup$x.shade.min,
      xmax = setup$x.shade.max,
      ymin = -Inf,
      ymax = Inf
    ) +
    
    # Add a horizontal dashed line at 0 (the baseline)
    ggplot2::geom_hline(
      yintercept = 0, 
      linetype = "dashed", 
      color = "black", 
      linewidth = 0.5
    ) +
    
    # Faint individual species lines ("spaghetti") - Non-outliers
    ggplot2::geom_line(
      data = dat_bg,
      ggplot2::aes(x = Time, y = Value, group = Var),
      color = "grey60", 
      alpha = 0.3, 
      linewidth = 0.5
    ) +
    
    # Colored outlier lines (thicker than background, thinner than mean)
    ggplot2::geom_line(
      data = dat_outliers,
      ggplot2::aes(x = Time, y = Value, color = Var),
      alpha = 0.8,
      linewidth = 0.8
    ) +
    
    # Thick aggregate mean line
    ggplot2::geom_line(
      data = dat_mean,
      ggplot2::aes(x = Time, y = Mean_Value),
      color = "black", 
      linewidth = 1.2
    ) +
    
    ggplot2::scale_x_continuous(
      breaks = round(seq(min(dat$Time, na.rm = TRUE), max(dat$Time, na.rm = TRUE), by = 5)),
      expand = c(0.01, 0.01)
    ) +
    
    # Apply a colorblind safe palette (end = 0.9 prevents colors from being too light/yellow)
    ggplot2::scale_color_viridis_d(
      name = "Highest Deviations:",
      option = "viridis",
      end = 0.9 
    ) +
    
    ggplot2::labs(
      y = "Fall Habitat Anomaly (%)",
      x = ggplot2::element_blank()
    ) +
    
    # Apply standard ecodata themes and titles
    ggplot2::ggtitle(paste0("Fall Thermal Habitat Anomaly \u2014 ", report, " Managed Species")) +
    ecodata::theme_ts() +
    ecodata::theme_title() +
    ggplot2::theme(
      legend.position = "bottom",
      legend.title = ggplot2::element_text(size = 9, face = "bold"),
      legend.text = ggplot2::element_text(size = 8)
    )
  
  return(p)
}

# Assign required ecodata attributes
attr(plot_thermal_habitat_anomaly_spaghetti, "report") <- c("MidAtlantic", "NewEngland")