#' plot thermal habitat anomaly
#'
#' Plots the Fall thermal habitat anomaly data set as a heatmap for the State of the Ecosystem report.
#'
#' @param shadedRegion Numeric vector. Years denoting the shaded region of the plot (most recent 10)
#' @param report Character string. Which SOE report ("MidAtlantic", "NewEngland")
#'
#' @return ggplot object
#'
#' @export
#'

plot_thermal_habitat_anomaly <- function(
    shadedRegion = NULL,
    report = "MidAtlantic"
) {
  # generate plot setup list (same for all plot functions)
  setup <- ecodata::plot_setup(shadedRegion = shadedRegion, report = report)
  
  # which report? Route to the appropriate EPU flag generated by create_thermal_habitat_anomaly
  if (report == "MidAtlantic") {
    filterEPU <- "MA"
  } else if (report == "NewEngland") {
    filterEPU <- "NE"
  } else {
    stop("For this indicator, the report must be either 'MidAtlantic' or 'NewEngland'")
  }
  
  # Filter the data object to the appropriate region
  dat <- ecodata::thermal_habitat_anomaly |>
    dplyr::filter(EPU == filterEPU)
  
  # Sort species by their average anomaly so similar trends cluster together visually on the y-axis
  sortNames <- dat |>
    dplyr::group_by(Var) |>
    dplyr::summarize(mean_anom = mean(Value, na.rm = TRUE), .groups = "drop") |>
    dplyr::arrange(mean_anom) |>
    dplyr::pull(Var)
  
  dat$Var <- factor(dat$Var, levels = sortNames)
  
  # Code for generating plot object p
  # ensure that setup list objects are called as setup$...
  
  p <- dat |>
    ggplot2::ggplot(ggplot2::aes(
      x = Time,
      y = forcats::fct_rev(Var),
      fill = Value
    )) +
    ggplot2::geom_tile(color = "white", linewidth = 0.2) +
    
    # Highlight last ten years OVER the tiles (so it slightly dims the shaded years)
    ggplot2::annotate(
      "rect",
      fill = setup$shade.fill,
      alpha = setup$shade.alpha,
      xmin = setup$x.shade.min,
      xmax = setup$x.shade.max,
      ymin = -Inf,
      ymax = Inf
    ) +
    
    # Continuous Viridis palette
    ggplot2::scale_fill_viridis_c(
      name = "Fall Habitat\nAnomaly (%)",
      na.value = "grey90"
    ) +
    
    ggplot2::scale_x_continuous(
      breaks = round(seq(min(dat$Time, na.rm = TRUE), max(dat$Time, na.rm = TRUE), by = 5)),
      expand = c(0, 0)
    ) +
    
    ggplot2::labs(
      x = ggplot2::element_blank(),
      y = ggplot2::element_blank()
    ) +
    
    ggplot2::theme_bw() +
    ggplot2::theme(
      legend.position = "right",
      legend.box = "vertical",
      legend.title = ggplot2::element_text(size = 9, face = "bold"),
      legend.text = ggplot2::element_text(size = 8),
      axis.text.x = ggplot2::element_text(size = 9, angle = 45, hjust = 1),
      axis.text.y = ggplot2::element_text(size = 9, face = "bold"),
      panel.grid.major = ggplot2::element_blank(),
      panel.grid.minor = ggplot2::element_blank()
    ) +
    
    # Apply standard ecodata themes and titles
    ggplot2::ggtitle(paste0("Fall Thermal Habitat Anomaly \u2014 ", report, " Managed Species")) +
    ecodata::theme_ts() +
    ecodata::theme_title()
  
  return(p)
}

# Assign required ecodata attributes
attr(plot_thermal_habitat_anomaly, "report") <- c("MidAtlantic", "NewEngland")